import { catchError } from "../../utilities/error.handler.js";

export const addProduct = catchError(async (req,res,next)=>{

})

export const getProduct = catchError(async (req,res,next)=>{

})

export const updateProduct = catchError(async (req,res,next)=>{
    
})

export const deleteProduct = catchError(async (req,res,next)=>{
    
})

export const getAllProducts = catchError(async (req,res,next)=>{

})

export const deleteAllProducts = catchError(async (req,res,next)=>{
    
})