import { catchError } from "../../utilities/error.handler.js";

export const addSubcategory = catchError(async (req,res,next)=>{

})

export const getSubcategory = catchError(async (req,res,next)=>{

})

export const updateSubcategory = catchError(async (req,res,next)=>{
    
})

export const deleteSubcategory = catchError(async (req,res,next)=>{
    
})

export const getAllSubcategories = catchError(async (req,res,next)=>{

})

export const deleteAllSubcategories = catchError(async (req,res,next)=>{
    
})