import { catchError } from "../../utilities/error.handler.js";

export const addBrand = catchError(async (req,res,next)=>{

})

export const getBrand = catchError(async (req,res,next)=>{

})

export const updateBrand = catchError(async (req,res,next)=>{
    
})

export const deleteBrand = catchError(async (req,res,next)=>{
    
})

export const getAllBrands = catchError(async (req,res,next)=>{

})

export const deleteAllBrands = catchError(async (req,res,next)=>{
    
})