import { catchError } from "../../utilities/error.handler.js";

export const addCategory = catchError(async (req,res,next)=>{

})

export const getCategory = catchError(async (req,res,next)=>{

})

export const updateCategory = catchError(async (req,res,next)=>{
    
})

export const deleteCategory = catchError(async (req,res,next)=>{
    
})

export const getAllCategories = catchError(async (req,res,next)=>{
    
})

export const deleteAllCategories = catchError(async (req,res,next)=>{
    
})